export const QueryKeys = {
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  LIST_USER: "LIST_USER",
  GET_USER: 'GET_USER',

  CREATE_HOSPITAL: 'CREATE_HOSPITAL',
  LIST_HOSPITAL: 'LIST_HOSPITAL'
};
