export const QueryKeys = {
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  LIST_USER: "LIST_USER",
  GET_USER: "GET_USER",

  CREATE_HOSPITAL: "CREATE_HOSPITAL",
  LIST_HOSPITAL: "LIST_HOSPITAL",
  GET_HOSPITAL_BY_ID: "GET_HOSPITAL_BY_ID",
  UPDATE_HOSPITAL: "UPDATE_HOSPITAL",
  DELETE_HOSPITAL_BY_ID: "DELETE_HOSPITAL_BY_ID",

  CREATE_DOCTOR: "CREATE_DOCTOR",
  LIST_DOCTOR: "LIST_DOCTOR",
  GET_DOCTOR_BY_ID: "GET_DOCTOR_BY_ID",
  UPDATE_DOCTOR: "UPDATE_DOCTOR",
  DELETE_DOCTOR_BY_ID: "DELETE_DOCTOR_BY_ID",

  LIST_DEPARTMENTS: "LIST_DEPARTMENTS",

  CREATE_STAFF: "CREATE_STAFF",
  LIST_STAFF: "LIST_STAFF",
};
